UPDATE chain SET chain = split_part(chain, '-', 2) WHERE exchange_name = 'okx'
DELETE FROM chain WHERE chain = '' AND exchange_name = 'digifinex'
UPDATE chain SET chain = 'BEP20' WHERE chain IN ('BSC', 'BNB Beacon Chain (BEP2)', 'BNB Smart Chain (BEP20)', 'BNB Smart Chain', 'BNB-BEP2', 'BEP20(BSC)', 'BEP20 (BSC)', 'BSC(BEP20)', 'BSC/BEP20', 'BSC(RACAV2)', 'BSC(BEP20)', 'BNB-BEP2', 'BNB/BEP2', 'BNB', 'bep20(bsc)')
UPDATE chain SET chain = 'ERC20' WHERE chain IN ('Ethereum (ERC20)', 'Ethereum', 'ETH/ERC20', 'ETH', 'Ethereum Classic', 'GRC20', 'CRC20', 'HRC20', 'NRC20', 'ARC20', 'ETHS', 'ETRC20', 'HRC20ETH', 'ARC20USDT', 'Ethereum (Proof-of-Work)', 'ETHF', 'ETHW', 'ETH2', 'ETHFAIR', 'Etherscan', 'ETHS', 'PETH', 'erc20')
UPDATE chain SET chain = 'TRC20' WHERE chain IN ('TRON', 'TRX', 'TRC10', 'Tron (TRC20)', 'trc20')
UPDATE chain SET chain = 'EVM' WHERE chain IN ('TENETEVM', 'SFLEVM', 'FRA(EVM)', 'VLX(EVM)', 'ASTAREVM', 'POINTEVM', 'FIBO', 'FEVM', 'PLBEVM', 'REBUSEVM', 'TELOS(EVM)', 'SysNEVM')
UPDATE chain SET chain = 'Avalanche' WHERE chain IN ('CAVAX', 'CCHAIN', 'AVAX C-Chain', 'AVAX-CCHAIN', 'Avalanche C')
UPDATE chain SET chain = 'Chiliz' WHERE chain IN ('CHZ', 'Chiliz', 'chz', 'CHZ20', 'Chiliz Chain(CHZ)', 'Chiliz Legacy Chain', 'ChilizLegacyChain', 'Chiliz Legacy Chain(CHZ)')
UPDATE chain SET chain = 'Neo' WHERE chain IN ('Neo Legacy', 'N3', 'NEO', 'Neo N3')
UPDATE chain SET chain = 'Harmony' WHERE chain IN ('Harmony/HRC20', 'Harmony')
UPDATE chain SET chain = 'Osmosis' WHERE chain IN ('Osmosis', 'OSMO')
UPDATE chain SET chain = 'Bitcoin' WHERE chain IN ('BTC', 'Bitcoin SV', 'Bitcoin', 'BTC(SegWit)')
UPDATE chain SET chain = 'Bifrost' WHERE chain IN ('Bifrost-Polkadot', 'BIFROSTKUSAMA')
UPDATE chain SET chain = 'zkSync' WHERE chain IN ('ZKSYNCERA', 'zkSync Lite(v1)', 'zkSync Era')
UPDATE chain SET chain = 'Dog' WHERE chain IN ('DOG20', 'DogeChain', 'Dogechain')
UPDATE chain SET chain = 'Arbitrum' WHERE chain IN ('Arbitrum-One', 'Arbitrum Nova', 'Arbitrum One (Bridged)')
UPDATE chain SET chain = 'Freeton' WHERE chain IN ('FREETON', 'Ton', 'TON')
UPDATE chain SET chain = 'Optimism' WHERE chain IN ('VELODROME(V2)-Optimism', 'Optimism (Bridged)', 'Optimism (V2)', 'OPTIMISM', 'Optimism (Circle)')
UPDATE chain SET chain = 'Arbitrum One' WHERE chain IN ('ARBITRUMONE', 'ARBITRUM', 'Arbitrum', 'ArbitrumOne', 'ARBITRUMETH', 'ArbitrumNova', 'Arbitrum-One', 'Arbitrum Nova', 'ArbitrumNova', 'Arbitrum One(Bridged)', 'Arbitrum One (Bridged)', 'Arbitrum One (Circle)')
UPDATE chain SET chain = 'Polygon' WHERE chain IN ('POLYGON', 'Polygon (Bridged)', 'Polygon (Circle)')